# Generated by Django 4.1.5 on 2023-01-26 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('userEmail', models.EmailField(max_length=100)),
                ('hobby', models.CharField(max_length=50)),
                ('favorite_movie', models.CharField(max_length=70)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentView', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=30)),
                ('movieName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviePolls.user')),
            ],
        ),
    ]
