# Generated by Django 4.1.5 on 2023-01-29 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviePolls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
    ]
