# Generated by Django 4.1.5 on 2023-01-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviePolls', '0002_remove_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
